### ISSUE TITLE
Books disappearing from Tome

### ISSUE THREAD

**Issue by Dubya72** [EccentricVamp/EccentricTome#25] opened 2022-08-15 19:52 UTC
**Versions**
 - Minecraft: [e.g. 1.18.2]
 - Eccentric Tome: [e.g. 1.8.0]

**Describe the bug**
In ATM7 and Direwolfs Modpack all the books in the tome were deleted except the current book loaded.  I don't know when it happed, but when I went to change books to look something up they were all gone.

**To Reproduce**
Don't know how to reproduce it.

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by EccentricVamp** [comment] 2022-08-17 00:40
Do you know if you had recently updated versions of the Eccentric Tome? (for example 1.3.1 → 1.8.0)

I'll try to investigate sometime this weekend.

**Comment by Dubya72** [comment] 2022-08-17 01:21
I didnt update anything. I had just downloaded Direwolfs pack and it
happened to me twice.  I cheated the books back in after it happened the
first time then it happened again.  I only played his pack week or so.

Then a few days ago I tried ATM7 and it happened after 2 or 3 days. Both
packs were unaltered from whatever the client downloaded.  Direwolfs pack
was on FTB launcher and ATM7 on Cursefoge launcher.

**Comment by EccentricVamp** [comment] 2022-08-20 21:49
I did some digging

* Investigated the raw tome data for 1.18.2 to see if there were any leaks. Couldn't find anything
* Searched for any known issues with NBTs (that's what Minecraft uses to store the Tome's data). Couldn't find anything
* Looked up the max NBT size in 1.18.2. It's 2 MiB which should be more than enough to store the guide books
    * It is possible one of the guide books in ATM and DIrewolf20 is doing some really crazy stuff with NBTs and causing the Eccentric Tome to go over the 2 MiB limit. But I can't fix it unless I know which one it is

I recommend gathering logs if you start playing either of the mod packs again. If it is exceeding the 2 MiB limit, that should show up in the logs. Another thing that might help is keeping track of which guide books you've put into the Eccentric Tome.

**Comment by Dubya72** [comment] 2022-08-20 21:53
I have been playing ATM7 since I last emailed you and it hasn't deleted any
books again so far. I will keep a list of the books I put in and send you
the crash report if it happens again.

Thanks,
CW

**Comment by EccentricVamp** [comment] 2022-08-21 16:39
I was doing some testing in 1.19.2 this morning. I think I managed to replicate the issue. Lost all the books in the Tome except for the one I was just using (Mystical Agriculture).

Books in tome
* Mystical Agriculture
* Cooking for Blockheads I
* Cooking for Blockheads II
* Cooking for Blockheads #NoFilter edition

I don't think it's an issue with the NBT size limit anymore.

I immediately tried to replicate the issue, but couldn't cause it to happen again. I'll continue investigating

**Comment by Dubya72** [comment] 2022-08-23 01:18
I had it happen to me again.  I started a new world (ATM7), so all the
books that you start the game with in the Tome were there, I put the quest
book in there that you get for completing the quest.  It worked fine after
that.  then I opened the EvilCraft book to look up something and that was
the book that was loaded.  I then went to the Blue Skies traders and got
the Blue Skies book.  I put it in the Tome and the rest of the books were
still there.  Then I turned on cheat mode, I always play with cheats
enabled in case of problems, and then I went out of cheat mode.  I then
traded the blue skies trader for the blue igniter thing and then I went to
look up something in the Blue Skies book and noticed that all the books
were gone except for the EvilCraft book which was loaded.

CW

**Comment by EccentricVamp** [comment] 2022-08-27 22:02
I spent 4 or 5 hours today trying to replicate this in different versions. I had the most (worst?) luck on 1.19.2 in creative mode.

To get a better look at what was happening, I added some additional logging. Managed to catch the items disappearing in the log. The Tome was successfully converted to Mystical Agriculture. But when the revert started, the items were gone.

```
[27Aug2022 12:45:58.771] [Server thread/DEBUG] [eccentrictome/]: Converted Eccentric Tome
[27Aug2022 12:45:58.772] [Server thread/DEBUG] [eccentrictome/]: {display:{Name:'{"translate":"eccentrictome.name","with":[{"color":"green","text":"Mystical Agriculture"}]}'},"eccentrictome:is_tome":1b,"eccentrictome:mods":{cookingforblockheads:{0:{Count:1b,id:"cookingforblockheads:crafting_book"},1:{Count:1b,id:"cookingforblockheads:no_filter_edition"},2:{Count:1b,id:"cookingforblockheads:recipe_book"}}},"patchouli:book":"mysticalagriculture:guide"}
[27Aug2022 12:46:06.061] [Server thread/DEBUG] [eccentrictome/]: Reverting Eccentric Tome
[27Aug2022 12:46:06.062] [Server thread/DEBUG] [eccentrictome/]: {display:{Name:'{"translate":"eccentrictome.name","with":[{"color":"green","text":"Mystical Agriculture"}]}'},"eccentrictome:is_tome":1b,"eccentrictome:mods":{},"eccentrictome:version":1,"patchouli:book":"mysticalagriculture:guide"}
```

I think I'm getting closer to the root cause.

I wasn't able to replicate it again after catching it in the logs. So, this will probably take another week. Thanks for your patience

**Comment by FyreAlchemage** [comment] 2022-08-28 02:47
I've been seeing this too in a pack I am working on, 1.18.2. The books in my tome are
- Materials and You (Tinkers Construct)
- Engineer's Manual (Immersive Engineering)
- Mahou Tsukai Knowledge Compendium (Mahou Tsukai)
- Decorating Your Home (Adorn)
- Food Book (Spice of Life Carrot)
- Big Book of Bees (Productive Bees)
- Lexica Botania (Botania)
- Biomepedia (BYG)
- Worn Notebook (Ars Nouveau)
- Sanguine Scientiem (Blood Magic)
- Thermalpedia (Thermal Series)
- On the Dynamics of Integration (Integrated Dynamics)
- LaserIO 101 (LaserIO)
- Encyclopedia Arcana (Malum)
Thankfully, I wrote a script so players can give themselves a new copy of a filled-out tome, so this error doesn't really impact us but it isn't ideal. I hope you track down the cause.

**Comment by EccentricVamp** [comment] 2022-09-17 16:41
I've pushed Eccentric Tome 1.9.0-beta which simplifies the mod's internal logic and expands logging. Since this bug doesn't cause crashes, the logging will be sent to `.minecraft/logs/debug.log` if your launcher supports it.

I'm going to be doing a bunch of testing this weekend (mostly just playing a personal mod pack). I'm trying to hunt down exactly when/where the bug occurs.

If you would like to assist the bug hunt, update to the beta version and send me a copy of your `debug.log` immediately after the bug occurs.

**Comment by ozhound** [comment] 2022-09-19 11:52
This just happened to me after many hours in a world and having most of the books added to the tome. This happened after a server restart. Im not sure if it is related, but another bug where i right clicked a mana spreader with a mana ring caused the mana spreader to eat the ring  voiding it aparently. i logged off and when i started the server and logged in the next day, only the active book (botania) was loaded.

**Comment by EccentricVamp** [comment] 2022-09-20 01:44
If you're still actively using the mod, I recommend upgrading to Eccentric Tome 1.9.0-beta. I was playing with it all weekend and encountered no issues. Fingers crossed that simplifying the logic fixed the bug since I still haven't been able to isolate the root cause.

> This happened after a server restart.

Good to know. I haven't included anything server-side in my testing. I might start testing that if 1.9.0 doesn't fix it

> Im not sure if it is related, but another bug where i right clicked a mana spreader with a mana ring caused the mana spreader to eat the ring voiding it

I think it's unrelated.

**Comment by ozhound** [comment] 2022-10-08 07:44
This happened again last night for me

i believe it occurs when you switch from the standard inventory screen to a book which is triggered by clicking on the tab at the bottom of the inventory screen. In my case and using the ATM7 Modpack i cycled through the 2 options i had available to me.

![2022-10-08_15 40 39](https://user-images.githubusercontent.com/3649237/194696212-5fbb0a0c-75a6-44a4-9ab4-d2997832a0b1.png)
![2022-10-08_15 40 42](https://user-images.githubusercontent.com/3649237/194696214-ee2a2baf-c21c-4d1b-8afc-d2e2fc3acd3f.png)
![2022-10-08_15 40 43](https://user-images.githubusercontent.com/3649237/194696215-d9d93f47-0fd6-420f-be0a-90c2517bad8f.png)

That last image shows a shortcut to opening the blue skies book. im unsure if this was loaded in the tome. maybe worth checking out

**Comment by EccentricVamp** [comment] 2022-10-08 16:19
@ozhound Do you know which version of Eccentric Tome you were using?

**Comment by ozhound** [comment] 2022-10-09 11:11
1.8.0

**Comment by EccentricVamp** [comment] 2022-11-13 22:13
After a bunch of hours of testing, I think I've fixed it. This issue should be fixed in Eccentric Tome 1.9.0, which I just released.

Let me know if you're still seeing the issue after the update.

**Comment by EccentricVamp** [comment] 2022-11-28 15:48
Closing this as completed. Leave a comment if you're still experiencing the issue.

**Closed** 2022-11-28 15:49 UTC
Labels: bug, help wanted

**Comment by EnterFor** [comment] 2023-01-16 04:04
@EccentricVamp Hello, excuse me, I am experiencing the same problem with the latest ATM7 module package, I noticed that the version in the package is 1.8.0, I found that you have fixed this problem.
My question is, is there a command to retrieve preset books?  Because I want to update this mod manually.
My English is not good, the above text is from the translation software

**Comment by EnterFor** [comment] 2023-01-16 04:06
I mean, is there any way to retrieve the birth book. I don't know if you can understand. I'm sorry

**Comment by EccentricVamp** [comment] 2023-01-20 01:22
@EnterFor sorry, there isn't a command. If you want to get it back, you'll need to add the books back in manually, probably using creative mode. Check this thread on Reddit for more info: https://www.reddit.com/r/allthemods/comments/v651np/how_to_get_eccentric_tome_back_after_losing_it/
