### ISSUE TITLE
Issue/Compat with Malum

### ISSUE THREAD

**Issue by Sixdd6** [EccentricVamp/EccentricTome#36] opened 2023-01-28 20:34 UTC
**Versions**
 - Minecraft: 1.18.2
 - Eccentric Tome 1.9.1
 - Malum 1.4.4.3

**Describe the bug**
When opening the Encyclopedia Arcana from Malum, while it is in an Eccentric Tome, the game crashes.

**To Reproduce**
Install both mods, add the book to the eccentric tome, try to open the book.

**Expected behavior**
Expected the book to open.

**Additional context**
I haven't checked yet as my modpack takes quite some time to launch but, this could be happening because the book is "fresh" as in it had never been opened before. I'm just guessing at this of course based on the top entry in the included crash report.

[crash-2023-01-28_14.24.42-client.txt](https://github.com/EccentricVamp/EccentricTome/files/10528209/crash-2023-01-28_14.24.42-client.txt)

Additional logs just in case they are needed:
[debug.log](https://github.com/EccentricVamp/EccentricTome/files/10528211/debug.log)
[latest.log](https://github.com/EccentricVamp/EccentricTome/files/10528213/latest.log)

**Comment by EccentricVamp** [comment] 2023-01-29 04:17
I wasn't able to figure out the root cause just from looking at the logs (thanks for including those, by the way). I'll start investigating sometime next week or weekend.

This might be something that needs to be fixed in [Malum](https://github.com/SammySemicolon/Malum-Mod) itself. If that is the case, I'll try to work with [SammySemicolon](https://github.com/SammySemicolon) on a fix.

**Comment by EccentricVamp** [comment] 2023-02-04 15:33
After investigating further, I've confirmed that this is an issue with [Metallum](https://beta.curseforge.com/minecraft/mc-mods/metallum) and is unrelated to Eccentric Tome.

Uninstalling Metallum should fix the issue.

**Closed** 2023-02-04 16:24 UTC
Labels: bug
